package model;
// Generated Jun 19, 2020 5:44:11 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "STUDENT",
        schema = "HR"
)
public class Student implements java.io.Serializable {

    private long id;
    private String studentid;
    private String name;
    private String classgrade;
    private String sex;
    private String contact;

    private Set<Address> address = new HashSet(0);
    private Set<Subjects> subjects = new HashSet(0);

    public Student() {
    }

    public Student(long id) {
        this.id = id;
    }

    public Student(long id, String studentid, String name, String classgrade, String sex, String contact, Set<Address> address, Set<Subjects> subjects) {
        this.id = id;
        this.studentid = studentid;
        this.name = name;
        this.classgrade = classgrade;
        this.sex = sex;
        this.contact = contact;
        this.address = address;
        this.subjects = subjects;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_student")
    @SequenceGenerator(name = "seq_student", sequenceName = "seq_student", allocationSize = 1, initialValue = 1)
    @Column(name = "Id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "STUDENTID", length = 50)
    public String getStudentid() {
        return this.studentid;
    }

    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    @Column(name = "NAME", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "CLASSGRADE", length = 50)
    public String getClassgrade() {
        return this.classgrade;
    }

    public void setClassgrade(String classgrade) {
        this.classgrade = classgrade;
    }

    @Column(name = "SEX", length = 50)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "CONTACT", length = 50)
    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "student")
    public Set<Address> getAddress() {
        return address;
    }

    public void setAddress(Set<Address> address) {
        this.address = address;
    }

    @OneToMany(cascade = CascadeType.ALL,mappedBy = "student")
    public Set<Subjects> getSubjects() {
        return subjects;
    }

    public void setSubjects(Set<Subjects> subjects) {
        this.subjects = subjects;
    }

}
